version: '3.1'

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1


volumes:
  jenkins-data:
  jenkins-docker-certs:

services:

  x_server:
    build: 
      context: .
      dockerfile: Dockerfile.remote
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports: 
        - "3010:22"

  jenkins:
    depends_on: 
      - dind
    user: root
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      # - $HOME/myprojects:/home
    environment:
      - DOCKER_HOST=tcp://10.5.0.8:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - $HOME:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

      